# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: The Telemetrix User's Guide For The Arduino UNO R4 Minima And WIFI
repo_url: https://github.com/MrYsLab/telemetrix-uno-r4
copyright: > # should remain a link to the original theme
  Copyright &copy; 2023 Alan Yorinks &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  Last Modified: August 
  12, 2023<br>


nav:
  - Introduction: index.md
  - Known Issues: issues.md
  - Installation:
      - Server:
          - Install The Arduino IDE: arduino_ide.md
          - Install the Telemetrix4Uno Library Into The Arduino IDE: server_library_installation.md
          - Select A Server From the Arduino IDE Examples Menu: server_selection.md
          - Server Configuration: server_config.md
      - Client:
          - Install Python 3.8+: python_3_verify.md
          - Create A Python Virtual Environment: venv.md
          - Installing The Python Client APIs: install_telemetrix.md
  - Usage:
      - Developing With Telemetrix:
          - General Principles: about_the_apis.md
          - Callbacks: callbacks.md
          - Application Creation: app_creation.md
          - Application Templates:
              - Arduino UNO R4 Minima:
                - Minima Threaded: template_minima_threaded.md
                - Minima AIO: template_minima_aio.md
              - Arduino UNO R4 WIFI:
                 - BLE AIO: template_ble.md
                 - USBSerial:
                    - USBSerial Threaded: template_usb_serial_threaded.md
                    - USBSerial AIO: template_usb_serial_aio.md
                 - WIFI:
                    - WIFI Threaded: template_wifi_threaded.md
                    - WIFI AIO: template_wifi_aio.md


      - The API References:
          - telemetrix_uno_r4_minima: telemetrix_minima_reference.md
          - telemetrix_uno_r4_minima_aio: telemetrix_minima_reference_aio.md
          - telemetrix_uno_r4_wifi: telemetrix_wifi_reference.md
          - telemetrix_uno_r4_wifi_aio: telemetrix_wifi_reference_aio.md
  - Downloading And Running The Examples: examples.md
  - About: about.md
  - License: license.md
# theme: windmill

theme:
  name: 'material'
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.footer

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [ telemetrix_uno_r4/wifi/telemetrix_uno_r4_wifi,
                   telemetrix_uno_r4/wifi/telemetrix_uno_r4_wifi_aio,
                   telemetrix_uno_r4/minima/telemetrix_uno_r4_minima,
                   telemetrix_uno_r4/minima/telemetrix_uno_r4_minima_aio ]



